### PR TITLE
Dashboard Rate and ETA (hard coded)

### PR DESCRIPTION
**Pull request by reedsturza**

### CODE REVIEW

**Review by justinszaro — APPROVED** [review]

**Comment by reedsturza** [comment]
The eta date will vary depending on your local system

**Comment by KyleSmilon** [comment]
@reedsturza I added the hard-coded value `21250` as Alex mentioned. This should be, if the system is at 100% consistently, around the number of overall jobs completed per hour.

**Comment by reedsturza** [comment]
> @reedsturza I added the hard-coded value `21250` as Alex mentioned. This should be, if the system is at 100% consistently, around the number of overall jobs completed per hour.

@KyleSmilon @AlexF301 Thanks for the update, that makes a lot more sense

**Comment by reedsturza** [comment]
Since we're restructuring the dashboard's html this pull request won't be useful anymore

**Pull request closed without merging**
