### PR TITLE
Docker compose image versions

### PR DESCRIPTION
**Pull request by evan-toyberg**
Specify the version numbers for images in the docker-compose.yml file. Prevents versioning issues with these services across production and development environments.

### CODE REVIEW

**Comment by evan-toyberg** [comment]
In order to make this work on your system, you will need to `rm -r ~/data/db` . Without doing this, your `mongo` will crash. If this doesn't work, then try `rm -r ~/data/*` .

**Comment by pereze03** [comment]
This seems to have fixed the issue. After removing the previous files like suggested, I was able to bring the system up and down without issue.

**Comment by nikovacs** [comment]
Since we are now specifying mongo version 5, does this mean we should be using `mongosh` instead of `mongo` in the health check? Afaik, `mongo` was pre-version 5, and `mongosh` replaced `mongo` in version 5.

**Comment by KyleSmilon** [comment]
> 

I did see this before and `mongo` was replaced in version 5 by `mongosh`. As far as changing it I am not sure.

**Comment by KyleSmilon** [comment]
> Since we are now specifying mongo version 5, does this mean we should be using `mongosh` instead of `mongo` in the health check? Afaik, `mongo` was pre-version 5, and `mongosh` replaced `mongo` in version 5.

I just added it and ran it locally and it worked fine I can push it to this branch if we want to go ahead with it.

**Comment by evan-toyberg** [comment]
Hold off on this for now, it looks like the mongo shell version is `5.0.1` and the server version is `4.4.6`. If we explicitly specify a version number, it will change one of these.

`4.4.6` did not work with `mongosh` locally for me. I'm investigating and trying to setup a dockerfile that will keep the versions the same.

**Comment by nikovacs** [comment]
Great

**Pull request merged**
