### PR TITLE
Added functions for s3 into client.py

### PR DESCRIPTION
**Pull request by cojitamboe15**
Added a function that checks if a valid connection to s3 could be made, and a function that puts a data object into a specified s3 bucket. Boto3 needs to be installed, and an AWS credentials file is needed at the root of the directory that contains "profile_name", as well as access and secret keys.

### CODE REVIEW

**Comment by jack11wagner** [comment]
Edwin, in order for these status checks to pass you are going to need to add the boto3 dependency to the `mirrulations/mirrulations-client/setup.cfg` file where it says `install_requires'.

**Comment by jack11wagner** [comment]
Edwin, in order for these status checks to pass you are going to need to add the boto3 dependency to the `mirrulations/mirrulations-client/setup.cfg` file where it says `install_requires'.

**Comment by jack11wagner** [comment]
Edwin, in order for these status checks to pass you are going to need to add the boto3 dependency to the 
`mirrulations/mirrulations-client/setup.cfg` file where it says `install_requires'.

**Comment by bjcoleman** [comment]
This change will also need tests.  This is where we need to push `boto3` "to the edge" by encapsulating it in a class or function.

**Comment by jack11wagner** [comment]
boto3=1.26.66

**Pull request closed without merging**
