### PR TITLE
Dashboard displays size of mirrulations bucket

### PR DESCRIPTION
**Pull request by AlexF301**
Will update the dashboard with the size of the mirrulations S3 bucket. Getting the size of the bucket occurs in the work_generator, this is then saved into redis.

Dashboard will call the JobStatistics class which accesses redis to get the associated key

### CODE REVIEW

**Comment by AlexF301** [comment]
Not Ready for merge

**Comment by AlexF301** [comment]
Ready for Review

Will update the dashboard with the size of the mirrulations bucket. Currently about 1400-1500 gb. To verify process locally, you will need to provide aws keys in the work_gen env. This can be done either manually or by running the dev setup script

**Comment by AlexF301** [comment]
Not sure why the unit test failed, running make on my system outputs no issues

**Comment by KyleSmilon** [comment]
The error occurs in the `test_work_generator_output_after_500_error` function in the tests. In my environment all the tests as well.

**Comment by cojitamboe15** [comment]
Looks good to me!

**Pull request merged**
