### PR TITLE
Totals dashboard

### PR DESCRIPTION
**Pull request by bryantqr**
regarding :Dashboard totals interface #114
not ready to be merged, still need documentation

### CODE REVIEW

**Comment by jack11wagner** [comment]
Is this PR ready for review?

**Comment by bryantqr** [comment]
Yes, its ready for review @jack11wagner @evan-toyberg

**Comment by evan-toyberg** [comment]
Not quite ready. I needed to change the API calls to use the RegulationsAPI class. It isn't passing the second mock. @bryantqr Can you take a look and see why?

**Comment by bryantqr** [comment]
@evan-toyberg I fixed the tests, now it's passing

**Comment by jack11wagner** [comment]
Is this ready to be reviewed now that the tests are passing?

**Comment by bryantqr** [comment]
@jack11wagner I would say yes, but it's better to confirm with @evan-toyberg

**Comment by evan-toyberg** [comment]
Yeah should be good for review

**Comment by jack11wagner** [comment]
Ok I see this is the class for retrieving the DataCounts, are you guys working toward implementing this into the Dashboard as well?

**Pull request merged**
