### PR TITLE
Exceptions for job queue

### PR DESCRIPTION
**Pull request by pereze03**
raising a job queue exception that will propagate out to the work server, work generator, and dashboard

### CODE REVIEW

**Comment by AlexF301** [comment]
Work Generator was Updated to handle exception arising from RabbitMQ. A custom Exception was created, and gets raised when an error in the job queue process occurs

**Comment by pereze03** [comment]
TODO:
 - Finishing writing tests for work server during get job error 
 - Log failure in work server and client when job queue errors 
 - Display "Unknown" on dashboard during job queue error

**Comment by pereze03** [comment]
Issue occurred when trying to resolve merge conflicts. Should be resolved.

**Comment by AlexF301** [comment]
Test coverage is over threshold of 95%. Ran system locally and operates as we have intended with no apparent issues. Manually tested in development by setting the heartbeat (timeout) of the channel to 1 second which essentially makes the connection drop a majority of the time. System handled the exceptions appropriately.

**Comment by pereze03** [comment]
This pull request is ready for review.

**Comment by cojitamboe15** [comment]
Ran the branch on my system and did not encounter any errors. Code looks good as well, great job guys!

**Pull request merged**
