### PR TITLE
adding BucketSize class

### PR DESCRIPTION
**Pull request by bryantqr**
Still need to specify the bucket or buckets and test

### CODE REVIEW

**Comment by AlexF301** [comment]
Currently experiencing:
```
botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the GetMetricStatistics operation: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
```

**Comment by AlexF301** [comment]
Going to have to add AWS keys to the work generator

**Comment by AlexF301** [comment]
Successfully able to get size of mirrulations bucket when providing AWS keys. Currently not saving value to Redis, just prints the size of the bucket in gb in the work generator

**Comment by bryantqr** [comment]
This pull request is ready to review

**Comment by AlexF301** [comment]
Writing to the actual dashboard will be in pull request #168. Broke process down into two seperate pull requests to avoid editing too many files.

**Comment by cojitamboe15** [comment]
Looks good to me as the classes were properly made with try except blocks, as well with proper tests.

**Pull request merged**
