### PR TITLE
reworked dashboard

### PR DESCRIPTION
**Pull request by reedsturza**

### CODE REVIEW

**Comment by reedsturza** [comment]
image

**Comment by reedsturza** [comment]
image

**Review by justinszaro — APPROVED** [review]

**Comment by reedsturza** [comment]
image

as of now, the javascript is throwing an error

**Comment by reedsturza** [comment]
image

**Comment by reedsturza** [comment]
image

**Review by reedsturza — COMMENTED** [review]
image

**Review by KyleSmilon — APPROVED** [review]
This looks good, think that the users now can easily understand what they are reading and there is still a good visual appeal.

**Comment by AlexF301** [comment]
Dashboard looks great. good work guys!

**Pull request merged**
